# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#default: &default
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000
#
#development:
#  <<: *default
#  database: db/development.sqlite3
#test:
#  <<: *default
#  database: db/test.sqlite3
#
#production:
#  <<: *default
#  database: db/production.sqlite3

# MYSQL DB

development:
  adapter: mysql2
  encoding: utf8
  database: xasdb
  username: root
  password:
  host: 10.0.0.40
  port: 3306
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: xasdb
  username: root
  password:
  host: 10.0.0.40
  port: 3306
  socket: /tmp/mysql.sock